<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Logan Shiller" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Welcome</title>
    <meta name="generator" content="Hugo 0.79.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/welcome/">Welcome</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         December 10, 2020 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="about-me" class="section level1">
<h1>About me</h1>
<div id="i-am-a-soon-to-be-graduate-of-ut.-clearly-i-am-very-excited-about-the-whole-thing.i-thought-it-would-be-fun-to-share-a-recipe-that-i-recently-tried.-my-all-time-favorite-food-is-probably-mac-and-cheese.-using-r-i-have-calcualted-the-metric-measurements-for-ingredients-and-using-python-i-have-shown-how-the-two-can-talk-to-eachother" class="section level5">
<h5>I am a soon to be graduate of UT. Clearly, I am very excited about the whole thing.I thought it would be fun to share a recipe that I recently tried. My all time favorite food is probably mac and cheese. Using r I have calcualted the metric measurements for ingredients and using python I have shown how the two can &quot;talk&quot; to eachother!</h5>
</div>
<div id="ingredients" class="section level2">
<h2>Ingredients</h2>
<div id="unexpected-cheddar14-of-the-block-grated---trader-joes" class="section level5">
<h5>Unexpected cheddar(1/4 of the block, grated) - Trader Joes</h5>
</div>
<div id="oz-mexican-blend-shredded-cheese" class="section level5">
<h5>6 oz mexican blend shredded cheese</h5>
</div>
<div id="c-flour" class="section level5">
<h5>1/8 c flour</h5>
</div>
<div id="c-butter" class="section level5">
<h5>1/8 c butter</h5>
</div>
<div id="c-milk" class="section level5">
<h5>2 c milk</h5>
</div>
<div id="tsp-each-saltpepperred-pepper-flakes-paprika" class="section level5">
<h5>1/4 tsp each salt,pepper,red pepper flakes, paprika</h5>
</div>
<div id="tbsp-minced-garlic" class="section level5">
<h5>1/2 tbsp minced garlic</h5>
</div>
<div id="oz-diced-onion-or-shallot" class="section level5">
<h5>4 oz diced onion or shallot</h5>
</div>
<div id="half-a-box-8-oz-of-your-favorite-noodle.-i-prefer-rigatoni" class="section level5">
<h5>half a box (8 oz) of your favorite noodle. I prefer rigatoni</h5>
</div>
</div>
<div id="instructions" class="section level2">
<h2>Instructions</h2>
<div id="in-a-pot-salt-your-water-and-set-to-a-boil.-cook-your-noodles-to-desired-doneness-and-strain.-in-another-medium-saucepan-melt-butter.-sautee-the-onion-and-garlic-until-translucent.-add-flour-and-stir-until-pale-yellow.-add-milk-and-stir-until-thickened.-turn-off-the-heat-and-add-your-cheese.-once-the-sauce-is-smooth-add-the-cheese-sauce-to-your-noodles-and-enjoy." class="section level4">
<h4>In a pot salt your water and set to a boil. Cook your noodles to desired doneness and strain. In another medium saucepan, melt butter. Sautee the onion and garlic until translucent. Add flour and stir until pale yellow. Add milk and stir until thickened. Turn off the heat and add your cheese. Once the sauce is smooth, add the cheese sauce to your noodles and enjoy.</h4>
<pre class="r"><code>ounces_to_grams &lt;- function(ounce) {
  gram &lt;- (ounce*28.349)
  return(gram)
}

ounces_to_grams(6)</code></pre>
<pre><code>## [1] 170.094</code></pre>
<pre class="r"><code>ounces_to_grams(8)</code></pre>
<pre><code>## [1] 226.792</code></pre>
<pre class="r"><code>ounces_to_grams(4)</code></pre>
<pre><code>## [1] 113.396</code></pre>
<pre class="r"><code>cup_to_milliliter &lt;- function(cup) {
  milliliter &lt;- (cup*236.588)
  return(milliliter)
}

cup_to_milliliter(1/8)</code></pre>
<pre><code>## [1] 29.5735</code></pre>
<pre class="r"><code>cup_to_milliliter(2)</code></pre>
<pre><code>## [1] 473.176</code></pre>
<pre class="r"><code>library(reticulate)</code></pre>
<div id="use-170.094-g-of-mexican-shredded-cheese-226.792-g-noodles-and-113.396-g-shallow-and-garlic.-use-29.57-ml-flour-and-butter-and-473.176-ml-milk." class="section level6">
<h6>Use 170.094 g of mexican shredded cheese, 226.792 g noodles, and 113.396 g shallow and garlic. Use 29.57 mL flour and butter and 473.176 mL milk.</h6>
</div>
</div>
</div>
<div id="python" class="section level2">
<h2>Python</h2>
<pre class="python"><code>import re</code></pre>
<div id="one-really-awesome-way-that-r-and-python-can-work-together-is-through-reticulate.-this-package-allows-the-user-to-access-python-from-r-markdown-and-seamlessly-transitioning-between-the-two-platforms.-another-very-conveneint-aspect-of-python-that-i-discovered-this-year-was-using-pandas.-pandas-makes-working-in-python-more-straight-forward-by-allowing-the-user-to-convert-a-list-or-numpy-array-into-a-pandas-dataframe.-this-makes-general-manipulating-of-data-cleaner-and-faster.-above-is-an-example-of-how-the-interface-between-r-and-python-works-using-reticulate-and-pandas.-i-found-this-example-online-using-code-that-we-learned-this-semester." class="section level6">
<h6>One really awesome way that R and Python can work together is through reticulate. This package allows the user to access python from R Markdown and seamlessly transitioning between the two platforms. Another very conveneint aspect of python that I discovered this year was using pandas. Pandas makes working in python more straight forward by allowing the user to convert a list or numpy array into a pandas dataframe. This makes general manipulating of data cleaner and faster. Above is an example of how the interface between R and Python works using reticulate and pandas. I found this example online using code that we learned this semester.</h6>
</div>
</div>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
