<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Logan Shiller" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../../../../img/favicon.ico">
    <title>Welcome </title>
    <meta name="generator" content="Hugo 0.79.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../../../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../../../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../../../../post/">BLOG</a></li>
        
        <li><a href="../../../../../projects/">PROJECTS</a></li>
        
        <li><a href="../../../../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../../../../post/2020/12/08/welcome/">Welcome </a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         December 8, 2020 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="about-me" class="section level1">
<h1>About me</h1>
<div id="i-am-a-soon-to-be-graduate-of-ut.-clearly-i-am-very-excited-about-the-whole-thing.i-thought-it-would-be-fun-to-share-a-recipe-that-i-recently-tried.-my-all-time-favorite-food-is-probably-mac-and-cheese.-using-r-i-have-calcualted-the-metric-measurements-for-ingredients.-using-python-i-have-shown-how-the-two-can-talk-to-eachother-using-an-example-from-class." class="section level5">
<h5>I am a soon to be graduate of UT. Clearly, I am very excited about the whole thing.I thought it would be fun to share a recipe that I recently tried. My all time favorite food is probably mac and cheese. Using r I have calcualted the metric measurements for ingredients. Using python I have shown how the two can &quot;talk&quot; to eachother, using an example from class.</h5>
<div class="figure">
<img src="../../../../../post/2020-12-08-welcome_files/macncheese.jpeg" />

</div>
</div>
<div id="ingredients" class="section level2">
<h2>Ingredients</h2>
<div id="unexpected-cheddar14-of-the-block-grated---trader-joes" class="section level5">
<h5>Unexpected cheddar(1/4 of the block, grated) - Trader Joes</h5>
</div>
<div id="oz-mexican-blend-shredded-cheese" class="section level5">
<h5>6 oz mexican blend shredded cheese</h5>
</div>
<div id="c-flour" class="section level5">
<h5>1/8 c flour</h5>
</div>
<div id="c-butter" class="section level5">
<h5>1/8 c butter</h5>
</div>
<div id="c-milk" class="section level5">
<h5>2 c milk</h5>
</div>
<div id="tsp-each-saltpepperred-pepper-flakes-paprika" class="section level5">
<h5>1/4 tsp each salt,pepper,red pepper flakes, paprika</h5>
</div>
<div id="tbsp-minced-garlic" class="section level5">
<h5>1/2 tbsp minced garlic</h5>
</div>
<div id="oz-diced-onion-or-shallot" class="section level5">
<h5>4 oz diced onion or shallot</h5>
</div>
<div id="half-a-box-8-oz-of-your-favorite-noodle.-i-prefer-rigatoni" class="section level5">
<h5>half a box (8 oz) of your favorite noodle. I prefer rigatoni</h5>
</div>
</div>
<div id="instructions" class="section level2">
<h2>Instructions</h2>
<div id="in-a-pot-salt-your-water-and-set-to-a-boil.-cook-your-noodles-to-desired-doneness-and-strain.-in-another-medium-saucepan-melt-butter.-sautee-the-onion-and-garlic-until-translucent.-add-flour-and-stir-until-pale-yellow.-add-milk-and-stir-until-thickened.-turn-off-the-heat-and-add-your-cheese.-once-the-sauce-is-smooth-add-the-cheese-sauce-to-your-noodles-and-enjoy." class="section level5">
<h5>In a pot salt your water and set to a boil. Cook your noodles to desired doneness and strain. In another medium saucepan, melt butter. Sautee the onion and garlic until translucent. Add flour and stir until pale yellow. Add milk and stir until thickened. Turn off the heat and add your cheese. Once the sauce is smooth, add the cheese sauce to your noodles and enjoy.</h5>
<pre class="r"><code>ounces_to_grams &lt;- function(ounce) {
  gram &lt;- (ounce*28.349)
  return(gram)
}

ounces_to_grams(6)</code></pre>
<pre><code>## [1] 170.094</code></pre>
<pre class="r"><code>ounces_to_grams(8)</code></pre>
<pre><code>## [1] 226.792</code></pre>
<pre class="r"><code>ounces_to_grams(4)</code></pre>
<pre><code>## [1] 113.396</code></pre>
<pre class="r"><code>cup_to_milliliter &lt;- function(cup) {
  milliliter &lt;- (cup*236.588)
  return(milliliter)
}

cup_to_milliliter(1/8)</code></pre>
<pre><code>## [1] 29.5735</code></pre>
<pre class="r"><code>cup_to_milliliter(2)</code></pre>
<pre><code>## [1] 473.176</code></pre>
<pre class="r"><code>library(reticulate)
library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ───────────────────────────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
## ✓ tibble  3.0.3     ✓ dplyr   1.0.1
## ✓ tidyr   1.1.1     ✓ stringr 1.4.0
## ✓ readr   1.4.0     ✓ forcats 0.5.0</code></pre>
<pre><code>## ── Conflicts ──────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<div id="use-170.094-g-of-mexican-shredded-cheese-226.792-g-noodles-and-113.396-g-shallow-and-garlic.-use-29.57-ml-flour-and-butter-and-473.176-ml-milk." class="section level6">
<h6>Use 170.094 g of mexican shredded cheese, 226.792 g noodles, and 113.396 g shallow and garlic. Use 29.57 mL flour and butter and 473.176 mL milk.</h6>
</div>
</div>
</div>
<div id="python" class="section level2">
<h2>Python</h2>
<pre class="python"><code>import re
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
df = sns.load_dataset(&#39;diamonds&#39;)
df

# tidying using python is similar to in R </code></pre>
<pre><code>##        carat        cut color clarity  depth  table  price     x     y     z
## 0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
## 1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
## 2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
## 3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
## 4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
## 5       0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
## 6       0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
## 7       0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
## 8       0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
## 9       0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39
## 10      0.30       Good     J     SI1   64.0   55.0    339  4.25  4.28  2.73
## 11      0.23      Ideal     J     VS1   62.8   56.0    340  3.93  3.90  2.46
## 12      0.22    Premium     F     SI1   60.4   61.0    342  3.88  3.84  2.33
## 13      0.31      Ideal     J     SI2   62.2   54.0    344  4.35  4.37  2.71
## 14      0.20    Premium     E     SI2   60.2   62.0    345  3.79  3.75  2.27
## 15      0.32    Premium     E      I1   60.9   58.0    345  4.38  4.42  2.68
## 16      0.30      Ideal     I     SI2   62.0   54.0    348  4.31  4.34  2.68
## 17      0.30       Good     J     SI1   63.4   54.0    351  4.23  4.29  2.70
## 18      0.30       Good     J     SI1   63.8   56.0    351  4.23  4.26  2.71
## 19      0.30  Very Good     J     SI1   62.7   59.0    351  4.21  4.27  2.66
## 20      0.30       Good     I     SI2   63.3   56.0    351  4.26  4.30  2.71
## 21      0.23  Very Good     E     VS2   63.8   55.0    352  3.85  3.92  2.48
## 22      0.23  Very Good     H     VS1   61.0   57.0    353  3.94  3.96  2.41
## 23      0.31  Very Good     J     SI1   59.4   62.0    353  4.39  4.43  2.62
## 24      0.31  Very Good     J     SI1   58.1   62.0    353  4.44  4.47  2.59
## 25      0.23  Very Good     G    VVS2   60.4   58.0    354  3.97  4.01  2.41
## 26      0.24    Premium     I     VS1   62.5   57.0    355  3.97  3.94  2.47
## 27      0.30  Very Good     J     VS2   62.2   57.0    357  4.28  4.30  2.67
## 28      0.23  Very Good     D     VS2   60.5   61.0    357  3.96  3.97  2.40
## 29      0.23  Very Good     F     VS1   60.9   57.0    357  3.96  3.99  2.42
## ...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
## 53910   0.70    Premium     E     SI1   60.5   58.0   2753  5.74  5.77  3.48
## 53911   0.57    Premium     E      IF   59.8   60.0   2753  5.43  5.38  3.23
## 53912   0.61    Premium     F    VVS1   61.8   59.0   2753  5.48  5.40  3.36
## 53913   0.80       Good     G     VS2   64.2   58.0   2753  5.84  5.81  3.74
## 53914   0.84       Good     I     VS1   63.7   59.0   2753  5.94  5.90  3.77
## 53915   0.77      Ideal     E     SI2   62.1   56.0   2753  5.84  5.86  3.63
## 53916   0.74       Good     D     SI1   63.1   59.0   2753  5.71  5.74  3.61
## 53917   0.90  Very Good     J     SI1   63.2   60.0   2753  6.12  6.09  3.86
## 53918   0.76    Premium     I     VS1   59.3   62.0   2753  5.93  5.85  3.49
## 53919   0.76      Ideal     I    VVS1   62.2   55.0   2753  5.89  5.87  3.66
## 53920   0.70  Very Good     E     VS2   62.4   60.0   2755  5.57  5.61  3.49
## 53921   0.70  Very Good     E     VS2   62.8   60.0   2755  5.59  5.65  3.53
## 53922   0.70  Very Good     D     VS1   63.1   59.0   2755  5.67  5.58  3.55
## 53923   0.73      Ideal     I     VS2   61.3   56.0   2756  5.80  5.84  3.57
## 53924   0.73      Ideal     I     VS2   61.6   55.0   2756  5.82  5.84  3.59
## 53925   0.79      Ideal     I     SI1   61.6   56.0   2756  5.95  5.97  3.67
## 53926   0.71      Ideal     E     SI1   61.9   56.0   2756  5.71  5.73  3.54
## 53927   0.79       Good     F     SI1   58.1   59.0   2756  6.06  6.13  3.54
## 53928   0.79    Premium     E     SI2   61.4   58.0   2756  6.03  5.96  3.68
## 53929   0.71      Ideal     G     VS1   61.4   56.0   2756  5.76  5.73  3.53
## 53930   0.71    Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
## 53931   0.71    Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
## 53932   0.70  Very Good     E     VS2   60.5   59.0   2757  5.71  5.76  3.47
## 53933   0.70  Very Good     E     VS2   61.2   59.0   2757  5.69  5.72  3.49
## 53934   0.72    Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
## 53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
## 53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
## 53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
## 53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
## 53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64
## 
## [53940 rows x 10 columns]</code></pre>
<pre class="python"><code>df[[&#39;x&#39;,&#39;y&#39;,&#39;z&#39;]].head()
</code></pre>
<pre><code>##       x     y     z
## 0  3.95  3.98  2.43
## 1  3.89  3.84  2.31
## 2  4.05  4.07  2.31
## 3  4.20  4.23  2.63
## 4  4.34  4.35  2.75</code></pre>
<div id="one-really-awesome-way-that-r-and-python-can-work-together-is-through-reticulate.-this-package-allows-the-user-to-access-python-from-r-markdown-and-seamlessly-transitioning-between-the-two-platforms.-another-very-conveneint-aspect-of-python-that-i-discovered-this-year-was-using-pandas.-pandas-makes-working-in-python-more-straight-forward-by-allowing-the-user-to-convert-a-list-or-numpy-array-into-a-pandas-dataframe.-this-makes-general-manipulating-of-data-cleaner-and-faster.-above-is-an-example-of-how-the-interface-between-r-and-python-works-using-reticulate-and-pandas.-i-used-an-example-that-i-really-enjoyed-learning-about-in-class-this-semester." class="section level6">
<h6>One really awesome way that R and Python can work together is through reticulate. This package allows the user to access python from R Markdown and seamlessly transitioning between the two platforms. Another very conveneint aspect of python that I discovered this year was using pandas. Pandas makes working in python more straight forward by allowing the user to convert a list or numpy array into a pandas dataframe. This makes general manipulating of data cleaner and faster. Above is an example of how the interface between R and Python works using reticulate and pandas. I used an example that I really enjoyed learning about in class this semester.</h6>
</div>
</div>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../../../../js/docs.min.js"></script>
<script src="../../../../../js/main.js"></script>

<script src="../../../../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
